os: linux
dist: trusty

cache:
  directories:
    - "$HOME/.composer/cache"
    - vendor

language: php
php:
  - '7.4'
  - '7.3'

branches:
  only:
    - develop
    - "/^.*[Ff]eature\\/.*$/"
    - "/^.*[rR]elease\\/.*$/"
    - "/^.*[bB]ug\\/.*$/"
    - "/^.*[Hh]otfix\\/.*$/"

jobs:
  fast_finish: true

env:
  global:
    - WORDPRESS_DB_USER=wp
    - WORDPRESS_DB_PASS=password
    - WORDPRESS_DB_NAME=wp_tests
    - WP_VERSION=5.5.1
    - WP_MULTISITE=0

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export DEV_BIN_PATH=bin
  - source $DEV_BIN_PATH/create-all-branches.sh
  - composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

before_script:
  - mysql -u root -e "GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO $WORDPRESS_DB_USER IDENTIFIED BY '$WORDPRESS_DB_PASS';"
  - mysql -u root -e "CREATE DATABASE $WORDPRESS_DB_NAME;"

script:
  - composer tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: change
