sudo: false
dist: trusty

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest

branches:
    only:
        - master
        - develop

before_install:
  - composer self-update

install:
  - composer install --no-interaction

script:
  - find src tests/php \( -name '*.php' \) -exec php -l {} \;
  - vendor/bin/phpunit
